### ISSUE TITLE
Внутренняя фрезеровка

### ISSUE THREAD

**Issue by yuranikspb** [XRay3D/GERBER_X2#11]
Как можно сделать внутреннюю фрезеровку ?
пример на скриншоте.
Форма этой фрезеровки может быть любая например змейкой.
![5555](https://user-images.githubusercontent.com/1639829/59347551-a139d280-8d1d-11e9-9af1-944a056b626d.JPG)

**Comment by XRay3D** [comment]
Если это апертура с отверстием то в сверловках.
![Снимок](https://user-images.githubusercontent.com/10693876/59526270-3afdad00-8ee1-11e9-9eeb-88bcd67af26b.PNG)
