### ISSUE TITLE
qt5 dll not found

### ISSUE THREAD

**Issue by techmike78** [XRay3D/GERBER_X2#14]
I downloaded the program for x86, I start and gives an error:
![изображение](https://user-images.githubusercontent.com/47521414/71557296-5c754f00-2a55-11ea-82e0-7978f0a9de43.png)
My PC: hp probook 470, w10x64
Installed at https://support.microsoft.com/en-us/help/2977003.
Rebooted, but the error is the same.
I tried to install Qt5 https://www.qt.io/download-thank-you, but it also did not help, maybe something else is needed?

**Comment by techmike78** [comment]
I forgot to write that such problems are only with version 0.7.8.3
For 0.7.8.2, there are a lot more files in the distribution and the program starts normally.

**Comment by XRay3D** [comment]
You need to put files from 0.7.8.3 on top of 0.7.8.2.

**Comment by techmike78** [comment]
> 
> 
> You need to put files from 0.7.8.3 on top of 0.7.8.2.

This should be written on the download page or in the instructions. Beginners will definitely get confused and abandon the program.
