### ISSUE TITLE
В параметрах инструмента, в блоке "Параметры резания", параметр "Отступ" нельзя сделать равным 0

### ISSUE THREAD

**Issue by Aleksei521** [XRay3D/GERBER_X2#18]
В параметрах инструмента, в блоке "Параметры резания", параметр "Отступ" нельзя сделать равным 0. Я так понимаю, если его сделать равным нулю, фреза должна делать один проход на данной глубине реза. Сейчас фреза делает два прохода, соответственно уходит в два раза больше времени на вырезание контура платы.

**Comment by XRay3D** [comment]
Отступ по x и y работает. Если сделать 0, то выборка площади будет вычисляться бесконечно в плоть до краха, так как не будет горизонтального приращения отступа.
