### ISSUE TITLE
Несанкционированная фрезеровка контура платы

### ISSUE THREAD

**Issue by Kurdl** [XRay3D/GERBER_X2#2]
Импортируемый гербер-файл не содержал контура платы.
От программы не требовалось его обрабатывать, 
Но программа все равно сгенерировала Г-код с управляющей траекторией "обхода контура", рассчитав его по граничным точкам, как прямоугольник.

**Comment by XRay3D** [comment]
> Но программа все равно сгенерировала Г-код с управляющей траекторией "обхода контура", рассчитав его по граничным точкам, как прямоугольник.
Так и задумывалось но данный функционал скорее всего будет перерабатываться.

**Comment by Kurdl** [comment]
Мне кажется, что не следует "резать" плату автоматически.
Это для начала. 
А вообще-то Gerber-формат содержит информацию о контурах платы.
FlatCAM его распознает. Главное - не повторить ошибку FlatCAM, когда она зачем-то строит траекторию обхода этого контура: https://cnc1310.ru/Picture/GetPicture/212
