### ISSUE TITLE
Не сохраняется инструмент в базе инструментов

### ISSUE THREAD

**Issue by Kurdl** [XRay3D/GERBER_X2#21]
Не сохраняется инструмент в базе инструментов

**Comment by XRay3D** [comment]
Это в мастере или дев ветке?

**Comment by Kurdl** [comment]
Я разобрался.
Чтобы прога вообще что-то запоминала, не следует размещать её в папке Program Files :)
Но юзеры должны быть предупреждены об этом! ;)
Однако у меня проблема по другому поводу - неправильно генерируется точка старта в УП (на форуме скриншоты).

**Comment by XRay3D** [comment]
Там будет работать если от админа стартовать. Так как всё хранится в папке с программой, а из этого следует что необходимо разрешение на перезапись в данной директории.
