### ISSUE TITLE
В панели параметров инструмента цифры не вводятся с клавиатуры

### ISSUE THREAD

**Issue by Kurdl** [XRay3D/GERBER_X2#3]
Не могу внести диаметр инструмента простым вводом цифр в поле "диаметр".
Сначала работают только кнопки инкремента/декремента.  После того, как 0.000 сменился на что угодно, ввод уже становится возможным.
Так же ведут себя другие элементы ввода.
Проверено на Win 7 x32  и Win 10 x64

**Comment by XRay3D** [comment]
Если выделить текст (можно двойным щелчком), то поверх выделенного всё вводится.
Это вопрос к разработчикам Qt.

**Comment by XRay3D** [comment]
Если выделить текст (можно двойным щелчком), то поверх выделенного всё вводится.
Это вопрос к разработчикам Qt, зачем именно так сделано.

**Comment by Kurdl** [comment]
А! Так это Qt! :) Вроде ко-то говорил C++
Респект! Люблю этот тролльский продукт! ;)
А зачем для создания УП необходимо сначала выделять графическую область?
Существует возможность работать по частям?

**Comment by XRay3D** [comment]
>А! Так это Qt! :) Вроде ко-то говорил C++

так он на С++ и написан. Это библиотеки, а не язык программирования.

Сейчас накидал свой контрол. Вроде работает как задумано, все стандартные заменю на свой, а то уже и самого досаждать начинает.

**Comment by Kurdl** [comment]
Чтобы не приставали к автору с глупостями, может мануал какой минимальный раздать? 
Для меня, например, не все очевидно в UI

**Comment by XRay3D** [comment]
Все руки ни как не дойдут, да и UI не закончен. Кстати перелазил, можете попробовать и сказать как стало, лучше или не очень.

**Comment by Kurdl** [comment]
Перезалил исходники? :) У меня компилить не чем.
По поводу контролов - не велика проблема в том, что вместо прямого ввода требуется щелкать кнопками или таскать ползунки. Мы ведь не вводим цифровое значение громкости в интерфейсе ОС.
Просто пользователь должен видеть характерный признак заблокированного для ввода контрола, например, - серый цвет.
А если еще предустановить начальные значения в рамках наиболее используемых - вообще не будет вопросов. Например, рабочий диаметр гравера - 0.1 мм. Угол - 30*  
Update: Решил кое-то проверить в программе, а она перестала открываться. Аварийно вылетает после появления на экране главного окна.

**Comment by XRay3D** [comment]
> 
> 
> Перезалил исходники? :) У меня компилить не чем.

Зачем, кому мои исходники сдались? Экзешники конечно.

**Comment by XRay3D** [comment]
У меня скаченное работает. А что за ошибка не пишет?

**Comment by Kurdl** [comment]
Дай прямую ссылку на дистрибутив.
Я качаю с кнопки Clone/Download архив GERBER_X2-master.zip
В нем вижу только исходники.

Ошибка - стандартная Windows "Прекращена работа программы... Искать решение в интернете..."
Причем это вчерашняя версия так себя ведет. Сегодня не запускался.

**Comment by XRay3D** [comment]
https://yadi.sk/d/L-laABnSVY4Ubw Качал сам у себя через браузер, всё работает.

**Comment by Kurdl** [comment]
x64 работает x32 вылетает. Причем, после сноса папки и перезаписи её, где-то хранится память о последнем проекте. В реестре?

**Comment by XRay3D** [comment]
Да

**Comment by XRay3D** [comment]
В реестре хранится список последних файлов. В 32 разрядной версии может не хватить памяти при открытии "больших" файлов или большого количества. В будущем исправлю когда пойму как.
