### ISSUE TITLE
Создание новой группы инструментов только вложенное

### ISSUE THREAD

**Issue by yuranikspb** [XRay3D/GERBER_X2#8]
Если зайти в настройки инструмента и ничего не нажимать то можно создать корневую группу, а вот если щелкнуть на любой инструмент или группу , то корневую уже не создать

**Comment by XRay3D** [comment]
Это не окончательный вариант. Всё переписано, ожидайте новой версии.

**Comment by XRay3D** [comment]
Это не окончательный вариант. Всё переписано и исправлено, ожидайте новой версии.
