### ISSUE TITLE
Высота перемещения

### ISSUE THREAD

**Issue by yuranikspb** [XRay3D/GERBER_X2#9]
Как задать высоту перемещения для каждого инструмента отдельно ? или хотябы для сверловки отдельно
Объясню: При гравировке дорожек высота в 0.3 мм нормально ( так как есть карта высот)
а вот при сверловке или вырезе платы нужно другую высоту ( так как не всегда есть карта высот ) и может одна из плат после вырез приподняться.

**Comment by XRay3D** [comment]
Перед сохранением применять необходимые настройки в данном окне.
![Снимок](https://user-images.githubusercontent.com/10693876/59526455-a182cb00-8ee1-11e9-8cab-03404566970f.PNG)
